### ISSUE TITLE
SODIMM Temperature partially shown

### ISSUE THREAD

**Issue by gluca** [Meliox/PVE-mods#113]
**Describe the bug**
The ùSODIMM temperatures are not sgown properly. Only last SODIMM is showed (in my case SODIMM 6)

**To Reproduce**
Install the new script, clear proxmox cache, refresh status page

**Expected behavior**
All SODIMM temperatures should be listed not only the last Bank

**Screenshots**

<img width="1238" height="518" alt="Image" src="https://github.com/user-attachments/assets/76fcc3f2-7a90-4768-978b-4706078de061" />

**Sensors output**
{
    "dell_smm-isa-00de": {
        "Adapter": "ISA adapter",
        "Processor Fan": {
            "fan2_input": 840.0,
            "fan2_min": 0.0,
            "fan2_max": 5755.0
        },
        "Other Fan": {
            "fan3_input": 5000.0,
            "fan3_min": 0.0,
            "fan3_max": 5000.0
        },
        "CPU": {
            "temp2_input": 47.0
        },
        "SODIMM": {
            "temp6_input": 38.0
        },
        "pwm1": {
            "pwm1": 64.0
        },
        "pwm2": {
            "pwm2": 64.0
        },
        "pwm3": {
            "pwm3": 127.5
        }
    },
    "coretemp-isa-0000": {
        "Adapter": "ISA adapter",
        "Package id 0": {
            "temp1_input": 49.0,
            "temp1_max": 92.0,
            "temp1_crit": 102.0,
            "temp1_crit_alarm": 0.0
        },
        "Core 0": {
            "temp2_input": 46.0,
            "temp2_max": 92.0,
            "temp2_crit": 102.0,
            "temp2_crit_alarm": 0.0
        },
        "Core 1": {
            "temp3_input": 45.0,
            "temp3_max": 92.0,
            "temp3_crit": 102.0,
            "temp3_crit_alarm": 0.0
        },
        "Core 2": {
            "temp4_input": 45.0,
            "temp4_max": 92.0,
            "temp4_crit": 102.0,
            "temp4_crit_alarm": 0.0
        },
        "Core 3": {
            "temp5_input": 45.0,
            "temp5_max": 92.0,
            "temp5_crit": 102.0,
            "temp5_crit_alarm": 0.0
        },
        "Core 4": {
            "temp6_input": 45.0,
            "temp6_max": 92.0,
            "temp6_crit": 102.0,
            "temp6_crit_alarm": 0.0
        },
        "Core 5": {
            "temp7_input": 44.0,
            "temp7_max": 92.0,
            "temp7_crit": 102.0,
            "temp7_crit_alarm": 0.0
        },
        "Core 6": {
            "temp8_input": 44.0,
            "temp8_max": 92.0,
            "temp8_crit": 102.0,
            "temp8_crit_alarm": 0.0
        },
        "Core 7": {
            "temp9_input": 43.0,
            "temp9_max": 92.0,
            "temp9_crit": 102.0,
            "temp9_crit_alarm": 0.0
        },
        "Core 8": {
            "temp10_input": 44.0,
            "temp10_max": 92.0,
            "temp10_crit": 102.0,
            "temp10_crit_alarm": 0.0
        },
        "Core 9": {
            "temp11_input": 45.0,
            "temp11_max": 92.0,
            "temp11_crit": 102.0,
            "temp11_crit_alarm": 0.0
        },
        "Core 10": {
            "temp12_input": 44.0,
            "temp12_max": 92.0,
            "temp12_crit": 102.0,
            "temp12_crit_alarm": 0.0
        },
        "Core 11": {
            "temp13_input": 43.0,
            "temp13_max": 92.0,
            "temp13_crit": 102.0,
            "temp13_crit_alarm": 0.0
        },
        "Core 12": {
            "temp14_input": 43.0,
            "temp14_max": 92.0,
            "temp14_crit": 102.0,
            "temp14_crit_alarm": 0.0
        },
        "Core 13": {
            "temp15_input": 45.0,
            "temp15_max": 92.0,
            "temp15_crit": 102.0,
            "temp15_crit_alarm": 0.0
        },
        "Core 14": {
            "temp16_input": 43.0,
            "temp16_max": 92.0,
            "temp16_crit": 102.0,
            "temp16_crit_alarm": 0.0
        },
        "Core 15": {
            "temp17_input": 43.0,
            "temp17_max": 92.0,
            "temp17_crit": 102.0,
            "temp17_crit_alarm": 0.0
        }
    },
    "coretemp-isa-0001": {
        "Adapter": "ISA adapter",
        "Package id 1": {
            "temp1_input": 48.0,
            "temp1_max": 92.0,
            "temp1_crit": 102.0,
            "temp1_crit_alarm": 0.0
        },
        "Core 0": {
            "temp2_input": 45.0,
            "temp2_max": 92.0,
            "temp2_crit": 102.0,
            "temp2_crit_alarm": 0.0
        },
        "Core 1": {
            "temp3_input": 45.0,
            "temp3_max": 92.0,
            "temp3_crit": 102.0,
            "temp3_crit_alarm": 0.0
        },
        "Core 2": {
            "temp4_input": 46.0,
            "temp4_max": 92.0,
            "temp4_crit": 102.0,
            "temp4_crit_alarm": 0.0
        },
        "Core 3": {
            "temp5_input": 45.0,
            "temp5_max": 92.0,
            "temp5_crit": 102.0,
            "temp5_crit_alarm": 0.0
        },
        "Core 4": {
            "temp6_input": 45.0,
            "temp6_max": 92.0,
            "temp6_crit": 102.0,
            "temp6_crit_alarm": 0.0
        },
        "Core 5": {
            "temp7_input": 46.0,
            "temp7_max": 92.0,
            "temp7_crit": 102.0,
            "temp7_crit_alarm": 0.0
        },
        "Core 6": {
            "temp8_input": 44.0,
            "temp8_max": 92.0,
            "temp8_crit": 102.0,
            "temp8_crit_alarm": 0.0
        },
        "Core 7": {
            "temp9_input": 43.0,
            "temp9_max": 92.0,
            "temp9_crit": 102.0,
            "temp9_crit_alarm": 0.0
        },
        "Core 8": {
            "temp10_input": 44.0,
            "temp10_max": 92.0,
            "temp10_crit": 102.0,
            "temp10_crit_alarm": 0.0
        },
        "Core 9": {
            "temp11_input": 44.0,
            "temp11_max": 92.0,
            "temp11_crit": 102.0,
            "temp11_crit_alarm": 0.0
        },
        "Core 10": {
            "temp12_input": 44.0,
            "temp12_max": 92.0,
            "temp12_crit": 102.0,
            "temp12_crit_alarm": 0.0
        },
        "Core 11": {
            "temp13_input": 45.0,
            "temp13_max": 92.0,
            "temp13_crit": 102.0,
            "temp13_crit_alarm": 0.0
        },
        "Core 12": {
            "temp14_input": 43.0,
            "temp14_max": 92.0,
            "temp14_crit": 102.0,
            "temp14_crit_alarm": 0.0
        },
        "Core 13": {
            "temp15_input": 43.0,
            "temp15_max": 92.0,
            "temp15_crit": 102.0,
            "temp15_crit_alarm": 0.0
        },
        "Core 14": {
            "temp16_input": 45.0,
            "temp16_max": 92.0,
            "temp16_crit": 102.0,
            "temp16_crit_alarm": 0.0
        },
        "Core 15": {
            "temp17_input": 42.0,
            "temp17_max": 92.0,
            "temp17_crit": 102.0,
            "temp17_crit_alarm": 0.0
        }
    }
}

**Additional context**

**Comment by Meliox** [comment]
I don't know if this works, but have a look https://discuss.cachyos.org/t/easiest-way-to-get-ram-temps/8688/10

**Comment by gluca** [comment]
I see 2. Sodimm 2 and sodimm 6

Gluca on my mobile
sorry for shorthess and typos

Il Mar 12 Ago 2025, 10:50 Meliox ***@***.***> ha scritto:

**Comment by Meliox** [comment]
Where do you see that?

**Comment by gluca** [comment]
Ok, if I issue sensors -j command, the output contains all SODIMM temperatures (see below), if I use the script
./pve-mod-gui-sensors.sh save-sensors-data
the output contains only SODIMM6
Here the sensors -j output (with a little formatting):

```	{"Adapter":"ISA adapter",
		"Processor Fan":{"fan1_input":1006.000000,"fan1_min":0.000000,"fan1_max":5755.000000},
		"Processor Fan":{"fan2_input":991.000000,"fan2_min":0.000000,"fan2_max":5755.000000},
		"Other Fan":{"fan3_input":594.000000,"fan3_min":0.000000,"fan3_max":5000.000000},
		"Other Fan":{"fan4_input":752.000000,"fan4_min":0.000000,"fan4_max":5000.000000},
		"CPU":{"temp1_input":45.000000},
		"CPU":{"temp2_input":49.000000},
		"SODIMM":{"temp3_input":34.000000},
		"SODIMM":{"temp4_input":38.000000},
		"SODIMM":{"temp5_input":43.000000},
		"SODIMM":{"temp6_input":33.000000},
		"pwm1":{"pwm1":127.500000},
		"pwm2":{"pwm2":127.500000},
		"pwm3":{"pwm3":127.500000},
		"pwm4":{"pwm4":127.500000}
	},
	"coretemp-isa-0000":
		{"Adapter":"ISA adapter",
		"Package id 0":{"temp1_input":45.000000,"temp1_max":92.000000,"temp1_crit":102.000000,"temp1_crit_alarm":0.000000},
		"Core 0":{"temp2_input":42.000000,"temp2_max":92.000000,"temp2_crit":102.000000,"temp2_crit_alarm":0.000000},
		"Core 1":{"temp3_input":40.000000,"temp3_max":92.000000,"temp3_crit":102.000000,"temp3_crit_alarm":0.000000},
		"Core 2":{"temp4_input":41.000000,"temp4_max":92.000000,"temp4_crit":102.000000,"temp4_crit_alarm":0.000000},
		"Core 3":{"temp5_input":41.000000,"temp5_max":92.000000,"temp5_crit":102.000000,"temp5_crit_alarm":0.000000},
		"Core 4":{"temp6_input":41.000000,"temp6_max":92.000000,"temp6_crit":102.000000,"temp6_crit_alarm":0.000000},
		"Core 5":{"temp7_input":40.000000,"temp7_max":92.000000,"temp7_crit":102.000000,"temp7_crit_alarm":0.000000},
		"Core 6":{"temp8_input":39.000000,"temp8_max":92.000000,"temp8_crit":102.000000,"temp8_crit_alarm":0.000000},
		"Core 7":{"temp9_input":40.000000,"temp9_max":92.000000,"temp9_crit":102.000000,"temp9_crit_alarm":0.000000},
		"Core 8":{"temp10_input":40.000000,"temp10_max":92.000000,"temp10_crit":102.000000,"temp10_crit_alarm":0.000000},
		"Core 9":{"temp11_input":41.000000,"temp11_max":92.000000,"temp11_crit":102.000000,"temp11_crit_alarm":0.000000},
		"Core 10":{"temp12_input":41.000000,"temp12_max":92.000000,"temp12_crit":102.000000,"temp12_crit_alarm":0.000000},
		"Core 11":{"temp13_input":39.000000,"temp13_max":92.000000,"temp13_crit":102.000000,"temp13_crit_alarm":0.000000},
		"Core 12":{"temp14_input":39.000000,"temp14_max":92.000000,"temp14_crit":102.000000,"temp14_crit_alarm":0.000000},
		"Core 13":{"temp15_input":40.000000,"temp15_max":92.000000,"temp15_crit":102.000000,"temp15_crit_alarm":0.000000},
		"Core 14":{"temp16_input":39.000000,"temp16_max":92.000000,"temp16_crit":102.000000,"temp16_crit_alarm":0.000000},
		"Core 15":{"temp17_input":39.000000,"temp17_max":92.000000,"temp17_crit":102.000000,"temp17_crit_alarm":0.000000}
	},
	"coretemp-isa-0001":
		{"Adapter":"ISA adapter",
		"Package id 1":{"temp1_input":50.000000,"temp1_max":92.000000,"temp1_crit":102.000000,"temp1_crit_alarm":0.000000},
		"Core 0":{"temp2_input":46.000000,"temp2_max":92.000000,"temp2_crit":102.000000,"temp2_crit_alarm":0.000000},
		"Core 1":{"temp3_input":46.000000,"temp3_max":92.000000,"temp3_crit":102.000000,"temp3_crit_alarm":0.000000},
		"Core 2":{"temp4_input":45.000000,"temp4_max":92.000000,"temp4_crit":102.000000,"temp4_crit_alarm":0.000000},
		"Core 3":{"temp5_input":46.000000,"temp5_max":92.000000,"temp5_crit":102.000000,"temp5_crit_alarm":0.000000},
		"Core 4":{"temp6_input":46.000000,"temp6_max":92.000000,"temp6_crit":102.000000,"temp6_crit_alarm":0.000000},
		"Core 5":{"temp7_input":45.000000,"temp7_max":92.000000,"temp7_crit":102.000000,"temp7_crit_alarm":0.000000},
		"Core 6":{"temp8_input":46.000000,"temp8_max":92.000000,"temp8_crit":102.000000,"temp8_crit_alarm":0.000000},
		"Core 7":{"temp9_input":45.000000,"temp9_max":92.000000,"temp9_crit":102.000000,"temp9_crit_alarm":0.000000},
		"Core 8":{"temp10_input":45.000000,"temp10_max":92.000000,"temp10_crit":102.000000,"temp10_crit_alarm":0.000000},
		"Core 9":{"temp11_input":45.000000,"temp11_max":92.000000,"temp11_crit":102.000000,"temp11_crit_alarm":0.000000},
		"Core 10":{"temp12_input":44.000000,"temp12_max":92.000000,"temp12_crit":102.000000,"temp12_crit_alarm":0.000000},
		"Core 11":{"temp13_input":45.000000,"temp13_max":92.000000,"temp13_crit":102.000000,"temp13_crit_alarm":0.000000},
		"Core 12":{"temp14_input":44.000000,"temp14_max":92.000000,"temp14_crit":102.000000,"temp14_crit_alarm":0.000000},
		"Core 13":{"temp15_input":45.000000,"temp15_max":92.000000,"temp15_crit":102.000000,"temp15_crit_alarm":0.000000},
		"Core 14":{"temp16_input":45.000000,"temp16_max":92.000000,"temp16_crit":102.000000,"temp16_crit_alarm":0.000000},
		"Core 15":{"temp17_input":44.000000,"temp17_max":92.000000,"temp17_crit":102.000000,"temp17_crit_alarm":0.000000}
	}
}

**Comment by gluca** [comment]
Uploaded both: sensors.json is the output from sensors -j while sensorsdata.json is the file produced by your script

[sensorsdata.json](https://github.com/user-attachments/files/22186251/sensorsdata.json)
[sensors.json](https://github.com/user-attachments/files/22186252/sensors.json)

**Comment by Meliox** [comment]
Perfect thank you. I see what the issue is. sensors.json is not a valid json per say. All memory nodes have the same key name, which means it will only save the last value "SODIMM":{"temp6_input":33.000000},. That needs fixing.

**Comment by gluca** [comment]
Has been always the same since you added the feature on my request, if I am
not wrong

Gluca on my mobile
sorry for shorthess and typos

Il Sab 6 Set 2025, 11:51 Meliox ***@***.***> ha scritto:

**Comment by Meliox** [comment]
That's true, but I could not identify the error based on the earlier information. lm-sensors unfortunately requires several workarounds.

**Comment by Meliox** [comment]
Fixed in above :)

<img width="915" height="221" alt="Image" src="https://github.com/user-attachments/assets/ad78b4be-a58a-458c-9d17-018c7fc5ac99" />

**Comment by gluca** [comment]
Still have the problem.
During installation the script still find only one SODIMM:
```
=== Preparing mod installation ===
[info] Root privileges verified.

=== Detecting CPU temperature sensors ===
[info] Detected CPU sensors (1): coretemp-isa-

Display temperatures for all cores [C] or average per CPU [a] (some newer AMD variants support per die)? (C/a): 
[info] Temperatures will be displayed for all cores.

=== Detecting RAM temperature sensors ===
[info] Detected RAM sensors (1): SODIMM

=== Detecting HDD/SSD temperature sensors ===
[warning] No HDD/SSD temperature sensors found.

=== Detecting NVMe temperature sensors ===
[warning] No NVMe temperature sensors found.

=== Detecting fan speed sensors ===
[info] Detected fan speed sensors (2): Processor Fan,Other Fan

Display fans reporting zero speed? (Y/n): 
```

output of sensors -j and of your script follows

[sensors.json](https://github.com/user-attachments/files/22194386/sensors.json)
[sensorsdata.json](https://github.com/user-attachments/files/22194385/sensorsdata.json)

**Comment by Meliox** [comment]
Sorry about that. Maybe something was lost in all the refactoring. I'll have a look.

**Comment by Meliox** [comment]
Hello, 

Maybe something was wrong in the download url in the readme... it pointed towards an old file as github has changed the url layout? Reference #128 


Anyhow these are the result from the current version. It's debugging, but there should not be a difference to real.

```bash
root@pve:~# bash pve-mod-gui-sensors.sh install

Installing the Proxmox VE sensors display mod...

=== Preparing mod installation ===
[info] Root privileges verified.
[warning] Remote debugging is used. Sensor readings from dump file /tmp/sensordata.json will be used.
[warning] Remote debugging is used. UPS readings from dump file /tmp/upsc.txt will be used.

=== Detecting CPU temperature sensors ===
[info] Detected CPU sensors (1): coretemp-isa-

Display temperatures for all cores [C] or average per CPU [a] (some newer AMD variants support per die)? (C/a):
[info] Temperatures will be displayed for all cores.

=== Detecting RAM temperature sensors ===
[info] Detected RAM sensors (4): SODIMM,SODIMM,SODIMM,SODIMM

=== Detecting HDD/SSD temperature sensors ===
[warning] No HDD/SSD temperature sensors found.

=== Detecting NVMe temperature sensors ===
[warning] No NVMe temperature sensors found.

=== Detecting fan speed sensors ===
[info] Detected fan speed sensors (1):

Display fans reporting zero speed? (Y/n):
[info] Zero-speed fans will be displayed.

Display temperatures in Celsius [C] or Fahrenheit [f]? (C/f):
[info] Using Celsius.

Enable UPS information? (y/N):
[info] UPS information will not be displayed.

=== Detecting System Information ===
type 1)
        Manufacturer: QEMU
        Product Name: Standard PC (i440FX + PIIX, 1996)
        Serial Number: Not Specified
type 2)

Enable system information? (1/2/n):
[info] System information will be displayed.

=== Creating backups of modified files ===
[info] Using default backup directory: /root/PVE-MODS
[info] Backup directory already exists: /root/PVE-MODS
[info] Created backup: /root/PVE-MODS/Nodes.pm.20250908_203705
[info] Created backup: /root/PVE-MODS/pvemanagerlib.js.20250908_203705

=== Inserting information retrieval code ===
[info] Sensors' retriever added to "/usr/share/perl5/PVE/API2/Nodes.pm".
[info] System information retriever added to "/usr/share/perl5/PVE/API2/Nodes.pm".

=== Creating temperature conversion helper ===
[info] Temperature helper configured for C.

=== Expanding StatusView space ===
[info] Expanded space in "/usr/share/pve-manager/js/pvemanagerlib.js".

=== Inserting temperature helper ===
[info] Temperature helper inserted successfully.

=== Making visual adjustments ===
[info] Inserted system_info widget.
[info] Inserted fan widget.
[info] Inserted ram widget.
[info] Inserted cpu widget.
[info] Added visual separator for modified items.
[info] Node summary box moved into its own container.

=== Finalizing installation ===
[info] Restarting PVE proxy...
[info] Installation completed.

Clear the browser cache to ensure all changes are visualized. (any key to continue):
```

<img width="1585" height="540" alt="Image" src="https://github.com/user-attachments/assets/d50d15fe-3f3c-43f7-a612-e6bbb57e7a21" />


I can see that you have more 2 CPU fans and 2 otherfans. Is it correct you would expect a total of 4.. If so, then fans have the same problem as ram :)

And it is incorrectly listed as 1 as well: "[info] Detected fan speed sensors (1):"

**Comment by gluca** [comment]
I will download it again. Can you provide a md5 hash so that I am sure is
the correct version?

Gluca on my mobile
sorry for shorthess and typos

Il Lun 8 Set 2025, 20:41 Meliox ***@***.***> ha scritto:

**Comment by Meliox** [comment]
```bash
root@pve:~# wget https://raw.githubusercontent.com/Meliox/PVE-mods/refs/heads/main/pve-mod-gui-sensors.sh
--2025-09-08 21:51:20--  https://raw.githubusercontent.com/Meliox/PVE-mods/refs/heads/main/pve-mod-gui-sensors.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 54205 (53K) [text/plain]
Saving to: ‘pve-mod-gui-sensors.sh’

pve-mod-gui-sensors.sh          100%[======================================================>]  52.93K  --.-KB/s    in 0.003s

2025-09-08 21:51:20 (14.8 MB/s) - ‘pve-mod-gui-sensors.sh’ saved [54205/54205]

root@pve:~# md5sum pve-mod-gui-sensors.sh
cbbe678ff56df730e7577bc30377cccb  pve-mod-gui-sensors.sh
root@pve:~#

```

**Comment by gluca** [comment]
Still the same, and you are right i see only one cpu fan and one system fan

<img width="3191" height="661" alt="Image" src="https://github.com/user-attachments/assets/a227ecaf-bef5-4afd-b432-8b346bf2b045" />

Here the exact sequence i do:
```
root@t7910:~#  md5sum pve-mod-gui-sensors.sh 
cbbe678ff56df730e7577bc30377cccb  pve-mod-gui-sensors.sh
root@t7910:~# chmod +x pve-mod-gui-sensors.sh 
root@t7910:~# ./pve-mod-gui-sensors.sh uninstall

Uninstalling the Proxmox VE sensors display mod...
=== Uninstalling Mod ===
[info] Root privileges verified.
[info] Using default backup directory: /root/PVE-MODS
[info] Restoring modified files...
Restoring latest Nodes.pm from backup: /root/PVE-MODS/Nodes.pm.20250907_092348 to "/usr/share/perl5/PVE/API2/Nodes.pm".
[info] Restored Nodes.pm successfully.
Restoring latest pvemanagerlib.js from backup: /root/PVE-MODS/pvemanagerlib.js.20250907_092348 to "/usr/share/pve-manager/js/pvemanagerlib.js".
[info] Restored pvemanagerlib.js successfully.
[info] Restarting PVE proxy...
```
--- clear browser cache and refresh ----
Everything reverted to standard Proxmox (not sending screenshot)
```
root@t7910:~# ./pve-mod-gui-sensors.sh install

Installing the Proxmox VE sensors display mod...

=== Preparing mod installation ===
[info] Root privileges verified.

=== Detecting CPU temperature sensors ===
[info] Detected CPU sensors (1): coretemp-isa-

Display temperatures for all cores [C] or average per CPU [a] (some newer AMD variants support per die)? (C/a): 
[info] Temperatures will be displayed for all cores.

=== Detecting RAM temperature sensors ===
[info] Detected RAM sensors (1): SODIMM

=== Detecting HDD/SSD temperature sensors ===
[warning] No HDD/SSD temperature sensors found.

=== Detecting NVMe temperature sensors ===
[warning] No NVMe temperature sensors found.

=== Detecting fan speed sensors ===
[info] Detected fan speed sensors (2): Processor Fan,Other Fan

Display fans reporting zero speed? (Y/n): 
[info] Zero-speed fans will be displayed.

Display temperatures in Celsius [C] or Fahrenheit [f]? (C/f): 
[info] Using Celsius.

Enable UPS information? (y/N): 
[info] UPS information will not be displayed.

=== Detecting System Information ===
type 1)
        Manufacturer: Dell Inc.
        Product Name: Precision Tower 7910
        Serial Number: ***************
type 2)
        Manufacturer: Dell Inc.
        Product Name: 0215PR
        Serial Number: ****************************

Enable system information? (1/2/n): 1
[info] System information will be displayed.

=== Creating backups of modified files ===
[info] Using default backup directory: /root/PVE-MODS
[info] Backup directory already exists: /root/PVE-MODS
[info] Created backup: /root/PVE-MODS/Nodes.pm.20250909_084149
[info] Created backup: /root/PVE-MODS/pvemanagerlib.js.20250909_084149

=== Inserting information retrieval code ===
[info] Sensors' retriever added to "/usr/share/perl5/PVE/API2/Nodes.pm".
[info] System information retriever added to "/usr/share/perl5/PVE/API2/Nodes.pm".

=== Creating temperature conversion helper ===
[info] Temperature helper configured for C.

=== Expanding StatusView space ===
[info] Expanded space in "/usr/share/pve-manager/js/pvemanagerlib.js".

=== Inserting temperature helper ===
[info] Temperature helper inserted successfully.

=== Making visual adjustments ===
[info] Inserted system_info widget.
[info] Inserted fan widget.
[info] Inserted ram widget.
[info] Inserted cpu widget.
[info] Added visual separator for modified items.
[info] Node summary box moved into its own container.

=== Finalizing installation ===
[info] Restarting PVE proxy...
```
--- clear browser cache and refresh ----
Still seeing only SODIMM 6 (see screenshot)

**Comment by gluca** [comment]
BTW i download the script by: wget https://raw.githubusercontent.com/Meliox/PVE-mods/refs/heads/main/pve-mod-gui-sensors.sh

**Comment by gluca** [comment]
if i run from command prompt: sensors -j 2>/dev/null | python3 -m json.tool (same you run in your script), i see exactly the same (only one SODIMM showed).
My pve python3 version is:
```
python3 --version
Python 3.13.5
```
Is there any test i can do to let you better understand?

**Comment by Meliox** [comment]
Ah. I think, I found the issue. I apply the python tool prior to correcting the content of the sensor output.   That is not applied in debug mode. I'll have that fixed later today as well as the fans :) 

 https://github.com/Meliox/PVE-mods/blob/67338aabbdfdc43ec07d231f1c0b6bc64f7527d0/pve-mod-gui-sensors.sh#L405

**Comment by gluca** [comment]
Confirm that if i remove the python3 -m json.tool from sensorcmd string, it shows all SODIMM temperatures (but still only one cpu fan)

**Comment by Meliox** [comment]
Thanks for confirming. That's also weird as python was needed to make it work following a new version of lm-sensors #105

**Comment by Meliox** [comment]
@gluca: I believe, I have finally resolved the issue. If you don't mind can you try the script in #134 and let me know?

**Comment by gluca** [comment]
Tested. It works with only a minor visual bug (SODIMM ids are displayed twice). See screenshot. 
Fans work perfectly.

<img width="1214" height="575" alt="Image" src="https://github.com/user-attachments/assets/00b9669d-37c2-4674-8069-7f6c5cf35f6b" />

**Comment by Meliox** [comment]
That's great, so far so good. How did the sodimms look during the installation information?

I did see this when amkng the change... But I am wondering if you are using the most recent copy?
Remember to remove the old copy first. 
https://raw.githubusercontent.com/Meliox/PVE-mods/6d5d5d3c738829f2db4910c342ed90db786f92a8/pve-mod-gui-sensors.sh

**Comment by gluca** [comment]
it was correctly enumerated
*Gianluca Magalotti*


Il giorno dom 14 set 2025 alle ore 22:29 Meliox ***@***.***>
ha scritto:

> *Meliox* left a comment (Meliox/PVE-mods#113)
> <https://github.com/Meliox/PVE-mods/issues/113#issuecomment-3289871397>
>
> That's great, so far so good. How did the sodimms look during the
> installation information?
>
> I did see this when amkng the change... But I am wondering if you are
> using the most recent copy?
> Remember to remove the old copy first.
>
> https://raw.githubusercontent.com/Meliox/PVE-mods/6d5d5d3c738829f2db4910c342ed90db786f92a8/pve-mod-gui-sensors.sh

**Comment by gluca** [comment]
The #134 i downloaded had the issue. the one you provided with this link, doesn't.

<img width="1225" height="589" alt="Image" src="https://github.com/user-attachments/assets/40a23a73-5cbb-4202-88e0-a925d3d247e2" />

**Comment by Meliox** [comment]
Perfect - then my feeling was correct. With that I can merge it. Thanks a lot for helping out with testing!
